import { Button, VerticalBox , ListView, StandardListView, HorizontalBox, StandardButton, ComboBox, ProgressIndicator} from "std-widgets.slint";
import { Msg } from "messages.slint";
import { StyleMetrics, TextEdit, LineEdit } from "std-widgets.slint";
import { Palette } from "std-widgets.slint";
export component AppWindow inherits Window {
    title: "Dali";
    min-width: 600px;
    min-height: 240px;
    preferred-width: 800px;
    preferred-height: 480px;
    default-font-size: 14px;
    default-font-weight: 500;
    background: StyleMetrics.dark-color-scheme ? rgb(36, 35, 37) : rgb(243, 242, 244);

    in-out property <[{a: int, b: string}]> msgs;
    in-out property <string> current-service: side_bar.model[side_bar.current-item].text;
    in-out property <length> scroll_y <=> msg.scrollview_y;
    out property <length> scroll_viewport_height:msg.scroll_viewport_height;
    out property <length> scroll_visible_height:msg.scroll_visible_height;
    callback get_input(string);
    callback clear();
    callback current_item_changed();

    HorizontalBox {
        padding-top: 30px;
        side_bar := StandardListView {

            width: 100px;
            // max-width: 200px;
            current-item: 3;

            model: [
                { text: "百川智能" },
                {
                    text: "深度求索",
                },
                {
                    text: "通义千问",
                },
                {
                    text: "月之暗面",
                },
                {
                    text: "零一万物",
                },
                {
                    text: "Groq",
                }
            ];
            current-item-changed => {
                current_item_changed();
            }
        }

        VerticalBox {
            padding-top: -20px;
            // HorizontalBox {
            //     alignment: LayoutAlignment.start;
            //     padding: -10px;
            //     Button {
            //         text: "🛜";
            //     }

            //     Button {
            //         text: "file";
            //     }

            //     Button {
            //         text: "图片";
            //     }
            // }

            msg := Msg {
                vertical-stretch: 1;
                msgs: root.msgs;
            }

            HorizontalBox {
                // padding: -5px;
                padding-bottom: -2px;
                padding-right: -2px;
                vertical-stretch: 0;
                LineEdit {
                    placeholder-text: "请输入您的问题";
                    accepted(text) => {
                        get_input(text);
                        self.text = "";
                        scroll_y = scroll_visible_height - scroll_viewport_height;
                    }
                }

                Button {
                    horizontal-stretch: 0;
                    icon: @image-url("clear.svg");
                    colorize-icon: true;
                    clicked => {
                        root.msgs = [];
                        scroll_y = 0px;
                        clear();
                    }
                }
            }
        }
    }
}
